/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated.checkout'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as NftsNftIdRouteImport } from './routes/nfts.$nftId'
import { Route as AuthenticatedOrdersOrderIdRouteImport } from './routes/_authenticated.orders.$orderId'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated.profile.index'
import { Route as AuthenticatedProfileWalletsRouteImport } from './routes/_authenticated.profile.wallets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const NftsNftIdRoute = NftsNftIdRouteImport.update({
  id: '/nfts/$nftId',
  path: '/nfts/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersOrderIdRoute =
  AuthenticatedOrdersOrderIdRouteImport.update({
    id: '/orders/$orderId',
    path: '/orders/$orderId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileWalletsRoute =
  AuthenticatedProfileWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/profile/wallets': typeof AuthenticatedProfileWalletsRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/profile/wallets': typeof AuthenticatedProfileWalletsRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/nfts/$nftId': typeof NftsNftIdRoute
  '/_authenticated/orders/$orderId': typeof AuthenticatedOrdersOrderIdRoute
  '/_authenticated/profile/wallets': typeof AuthenticatedProfileWalletsRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/signup'
    | '/checkout'
    | '/profile'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/profile/wallets'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/signup'
    | '/checkout'
    | '/nfts/$nftId'
    | '/orders/$orderId'
    | '/profile/wallets'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/login'
    | '/signup'
    | '/_authenticated/checkout'
    | '/_authenticated/profile'
    | '/nfts/$nftId'
    | '/_authenticated/orders/$orderId'
    | '/_authenticated/profile/wallets'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  NftsNftIdRoute: typeof NftsNftIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/nfts/$nftId': {
      id: '/nfts/$nftId'
      path: '/nfts/$nftId'
      fullPath: '/nfts/$nftId'
      preLoaderRoute: typeof NftsNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders/$orderId': {
      id: '/_authenticated/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/wallets': {
      id: '/_authenticated/profile/wallets'
      path: '/wallets'
      fullPath: '/profile/wallets'
      preLoaderRoute: typeof AuthenticatedProfileWalletsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileWalletsRoute: typeof AuthenticatedProfileWalletsRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileWalletsRoute: AuthenticatedProfileWalletsRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedOrdersOrderIdRoute: typeof AuthenticatedOrdersOrderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedOrdersOrderIdRoute: AuthenticatedOrdersOrderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  NftsNftIdRoute: NftsNftIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
